"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { useAppContext } from "@/components/providers/AppProvider";
import credentialCompromise from "@/data/scenarios/credential-compromise.json";
import ransomware from "@/data/scenarios/ransomware-lateral-movement.json";
import insiderThreat from "@/data/scenarios/insider-threat-data-staging.json";

type EvidenceType = "AUTH_LOG" | "NETWORK_LOG" | "DATA_LOG" | "SYSTEM_LOG" | "ENDPOINT_LOG";
type Scenario = typeof credentialCompromise;
const scenarios: Record<string, Scenario> = { "credential-compromise": credentialCompromise, "ransomware-lateral-movement": ransomware as Scenario, "insider-threat-data-staging": insiderThreat as Scenario };
const typeStyles: Record<EvidenceType, string> = { AUTH_LOG: "bg-low/15 text-low border-low/30", NETWORK_LOG: "bg-network/15 text-network border-network/30", DATA_LOG: "bg-critical/15 text-critical border-critical/30", SYSTEM_LOG: "bg-medium/15 text-medium border-medium/30", ENDPOINT_LOG: "bg-cyan/15 text-cyan border-cyan/30" };
const typeColors: Record<EvidenceType, string> = { AUTH_LOG: "#4096FF", NETWORK_LOG: "#B37FEB", DATA_LOG: "#FF4D4F", SYSTEM_LOG: "#FFA940", ENDPOINT_LOG: "#13C2C2" };

export default function InvestigationView({ params }: { params: { id: string } }) {
  const { getInvestigation } = useAppContext();
  const stored = getInvestigation(params.id);
  const scenario = scenarios[stored?.scenarioId ?? params.id] ?? credentialCompromise;
  const [selectedHypothesis, setSelectedHypothesis] = useState<string | null>(null);
  const [selectedEvidence, setSelectedEvidence] = useState<string | null>(null);
  const [tab, setTab] = useState<"timeline" | "graph">("timeline");
  const [expanded, setExpanded] = useState<string | null>(null);
  const [checkedGaps, setCheckedGaps] = useState<string[]>([]);
  const selected = scenario.hypotheses.find((hypothesis) => hypothesis.id === selectedHypothesis);
  const visibleEvidence = useMemo(() => scenario.evidenceItems.filter((item) => !selectedHypothesis || item.linkedHypotheses.includes(selectedHypothesis)), [scenario, selectedHypothesis]);
  const visibleEvents = scenario.timeline.filter((event) => visibleEvidence.some((item) => item.id === event.evidenceId));
  const graphNodes = selected?.path ?? ["Internet", "VPN Gateway", "File Server", "Cloud Storage"];

  return <main className="min-h-screen bg-canvas p-4 text-slate-100 lg:p-5">
    <header className="mb-4 flex flex-wrap items-end justify-between gap-3 border-b border-border pb-4"><div><Link href="/" className="font-mono text-[10px] uppercase tracking-[.16em] text-cyan hover:text-slate-100">← Dashboard</Link><p className="mt-2 font-mono text-[10px] uppercase tracking-[.16em] text-slate-500">Investigation / {params.id}</p><h1 className="mt-1 text-xl font-semibold">{stored?.title ?? scenario.name}</h1><p className="mt-1 max-w-3xl text-xs text-slate-500">{scenario.summary}</p></div><button className="rounded border border-border bg-panel px-3 py-2 text-xs text-slate-300 hover:border-border-hover">Export report</button></header>
    <div className="grid min-h-[calc(100vh-118px)] gap-4 xl:grid-cols-[30fr_45fr_25fr]">
      <aside className="flex min-h-0 flex-col rounded-xl border border-border bg-panel p-3">
        <div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold">Evidence feed</h2><span className="font-mono text-[10px] text-slate-500">{visibleEvidence.length} ITEMS</span></div>
        <div className="min-h-0 space-y-2 overflow-y-auto pr-1 xl:max-h-[calc(100vh-172px)]">{scenario.evidenceItems.map((item) => { const visible = !selectedHypothesis || item.linkedHypotheses.includes(selectedHypothesis); const active = selectedEvidence === item.id; return <button key={item.id} onClick={() => { setSelectedEvidence(item.id); setTab("timeline"); }} className={`w-full rounded-lg border p-3 text-left transition ${active ? "border-primary bg-primary/10" : "border-border bg-panel-secondary hover:border-border-hover"} ${visible ? "opacity-100" : "opacity-25"}`}><div className="flex items-center justify-between gap-2"><span className={`rounded border px-1.5 py-0.5 font-mono text-[9.5px] ${typeStyles[item.type as EvidenceType]}`}>{item.type}</span><time className="font-mono text-[10px] text-slate-500">{item.timestamp}</time></div><p className="mt-2 text-xs leading-5 text-slate-300">{item.summary}</p><p className="mt-2 font-mono text-[9px] text-slate-600">LINKED: {item.linkedHypotheses.join(" · ").toUpperCase()}</p></button> })}</div>
      </aside>
      <section className="flex min-h-[480px] flex-col rounded-xl border border-border bg-panel p-4">
        <div className="flex gap-5 border-b border-border"><button onClick={() => setTab("timeline")} className={`border-b-2 pb-3 text-sm ${tab === "timeline" ? "border-cyan text-cyan" : "border-transparent text-slate-500"}`}>Timeline</button><button onClick={() => setTab("graph")} className={`border-b-2 pb-3 text-sm ${tab === "graph" ? "border-cyan text-cyan" : "border-transparent text-slate-500"}`}>Attack Graph</button><span className="ml-auto pt-1 font-mono text-[10px] text-slate-600">{selected ? "FILTERED THEORY" : "ALL EVIDENCE"}</span></div>
        {tab === "timeline" ? <Timeline events={visibleEvents} evidence={scenario.evidenceItems} selectedEvidence={selectedEvidence} /> : <AttackGraph nodes={graphNodes} selected={selected} />}
      </section>
      <aside className="min-h-0 space-y-4 xl:max-h-[calc(100vh-118px)] xl:overflow-y-auto xl:pr-1">
        <section className="rounded-xl border border-border bg-panel p-3"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold">Hypotheses</h2>{selected && <button onClick={() => setSelectedHypothesis(null)} className="font-mono text-[10px] text-cyan">CLEAR</button>}</div><div className="space-y-2">{scenario.hypotheses.map((hypothesis) => { const active = selectedHypothesis === hypothesis.id; return <article key={hypothesis.id} className={`rounded-lg border transition ${active ? "border-primary bg-primary/10" : "border-border bg-panel-secondary"}`}><button onClick={() => setSelectedHypothesis(active ? null : hypothesis.id)} className="w-full p-3 text-left"><div className="flex gap-2"><h3 className="flex-1 text-xs font-semibold leading-5 text-slate-100">{hypothesis.title}</h3><span className="font-mono text-xs text-cyan">{hypothesis.confidence}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded bg-border"><div className="h-full rounded bg-primary" style={{ width: `${hypothesis.confidence}%` }} /></div><p className="mt-2 text-[11px] leading-4 text-slate-400">{hypothesis.summary}</p><div className="mt-2 flex gap-3 font-mono text-[9px]"><span className="text-safe">+ {hypothesis.supporting} SUPPORT</span><span className="text-critical">− {hypothesis.conflicting} CONFLICT</span></div><div className="mt-2 flex flex-wrap gap-1">{hypothesis.techniques.map((technique) => <span key={technique} className="rounded bg-border px-1.5 py-0.5 font-mono text-[9px] text-slate-400">{technique}</span>)}</div></button><button onClick={() => setExpanded(expanded === hypothesis.id ? null : hypothesis.id)} className="w-full border-t border-border px-3 py-2 text-left font-mono text-[10px] text-cyan">{expanded === hypothesis.id ? "− HIDE REASONING" : "+ FULL REASONING"}</button>{expanded === hypothesis.id && <p className="border-t border-border px-3 py-2 text-[11px] leading-5 text-slate-400">{hypothesis.reasoning}</p>}</article> })}</div></section>
        <section className="rounded-xl border border-border bg-panel p-3"><h2 className="text-sm font-semibold">Missing Evidence <span className="font-normal text-slate-500">— What to check next</span></h2><div className="mt-3 space-y-3">{scenario.evidenceGaps.map((gap) => <label key={gap.id} className="flex cursor-pointer gap-2.5 rounded-lg border border-border bg-panel-secondary p-2.5"><input type="checkbox" checked={checkedGaps.includes(gap.id)} onChange={() => setCheckedGaps((current) => current.includes(gap.id) ? current.filter((id) => id !== gap.id) : [...current, gap.id])} className="mt-0.5 accent-cyan" /><span><span className={`block text-[11px] leading-4 ${checkedGaps.includes(gap.id) ? "text-slate-600 line-through" : "text-slate-300"}`}>{gap.description}</span><span className="mt-1 block font-mono text-[9px] leading-4 text-slate-500"><b className="font-normal text-safe">↑ {gap.strengthens}</b> · <b className="font-normal text-critical">↓ {gap.weakens}</b></span></span></label>)}</div></section>
      </aside>
    </div>
  </main>;
}

function Timeline({ events, evidence, selectedEvidence }: { events: Scenario["timeline"]; evidence: Scenario["evidenceItems"]; selectedEvidence: string | null }) {
  const positions = events.map((_, index) => 10 + (index * 80) / Math.max(events.length - 1, 1));
  return <div className="flex flex-1 flex-col justify-center overflow-x-auto py-10"><div className="min-w-[590px] px-3"><div className="relative h-64"><svg viewBox="0 0 1000 180" className="absolute left-0 top-14 h-32 w-full overflow-visible"><defs><linearGradient id="flow" x1="0" x2="1"><stop stopColor="#2F54EB"/><stop offset="1" stopColor="#13C2C2"/></linearGradient></defs><path d="M45 90 C280 45 650 142 955 90" fill="none" stroke="url(#flow)" strokeWidth="3" opacity=".8"/>{events.map((event, index) => { const item = evidence.find((entry) => entry.id === event.evidenceId)!; const x = 45 + (910 * index) / Math.max(events.length - 1, 1); const y = 90 + Math.sin(index * 1.9) * 24; const active = selectedEvidence === event.evidenceId; return <g key={event.evidenceId}><circle cx={x} cy={y} r={active ? 15 : 10} fill={typeColors[item.type as EvidenceType]} className={active ? "animate-pulse" : ""} stroke="#0A0E17" strokeWidth="5"/><text x={x} y={y - 38} textAnchor="middle" fill="#13C2C2" fontSize="12" fontFamily="monospace">{event.technique}</text></g> })}</svg>{events.map((event, index) => { const item = evidence.find((entry) => entry.id === event.evidenceId)!; return <div key={event.evidenceId} className="absolute top-[163px] w-28 -translate-x-1/2 text-center" style={{ left: `${positions[index]}%` }}><p className="font-mono text-[10px] text-slate-500">{item.timestamp}</p><p className="mt-1 text-[11px] leading-4 text-slate-300">{event.label}</p></div> })}</div></div><div className="mx-auto mt-3 flex flex-wrap justify-center gap-x-3 gap-y-1 font-mono text-[9px] text-slate-500">{Object.entries(typeColors).map(([type, color]) => <span key={type}><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full" style={{ background: color }} />{type.replace("_", " ")}</span>)}</div></div>;
}

function AttackGraph({ nodes, selected }: { nodes: string[]; selected: Scenario["hypotheses"][number] | undefined }) {
  const points = [[75, 140], [260, 80], [475, 165], [675, 85], [875, 140]]; const shown = nodes.slice(0, 5);
  return <div className="flex flex-1 items-center overflow-x-auto py-8"><div className="min-w-[700px] flex-1"><svg viewBox="0 0 950 280" className="h-[300px] w-full"><defs><filter id="glow"><feGaussianBlur stdDeviation="6" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#FF4D4F"/></marker></defs>{points.slice(0, shown.length - 1).map((point, index) => <path key={index} d={`M ${point[0] + 50} ${point[1]} C ${point[0] + 110} ${point[1] - 90}, ${points[index + 1][0] - 110} ${points[index + 1][1] + 90}, ${points[index + 1][0] - 50} ${points[index + 1][1]}`} fill="none" stroke="#FF4D4F" strokeWidth="3" strokeDasharray="8 8" markerEnd="url(#arrow)" className="attack-trace" opacity={selected ? 1 : .35}/>)}{shown.map((node, index) => <g key={node} transform={`translate(${points[index][0]},${points[index][1]})`}><rect x="-50" y="-25" width="100" height="50" rx="8" fill="#151D2E" stroke={selected ? "#FF4D4F" : "#2A3B57"} strokeWidth="1.5" filter={selected ? "url(#glow)" : undefined}/><text textAnchor="middle" y="-3" fill="#E5E7EB" fontSize="12">{node}</text><text textAnchor="middle" y="13" fill="#64748B" fontSize="9" fontFamily="monospace">{index === 0 ? "ENTRY" : index === shown.length - 1 ? "TARGET" : "COMPROMISED"}</text></g>)}</svg><p className="text-center font-mono text-[10px] text-slate-500">{selected ? `ACTIVE PATH: ${selected.title.toUpperCase()}` : "SELECT A HYPOTHESIS TO TRACE A THEORY"}</p></div></div>;
}
