"use client";

import Link from "next/link";
import { useAppContext } from "@/components/providers/AppProvider";

const severityStyles = { critical: "bg-critical/15 text-critical border-critical/30", high: "bg-medium/15 text-medium border-medium/30", medium: "bg-low/15 text-low border-low/30", low: "bg-safe/15 text-safe border-safe/30" };
const howItWorks = [["01", "Define your infrastructure", "Map your assets, connections, and trust boundaries"], ["02", "Paste incident logs", "Feed raw security logs from any source"], ["03", "Investigate the story", "Explore competing hypotheses, attack paths, and evidence gaps"]];

export default function DashboardPage() {
  const { organization, investigations, hydrated } = useAppContext();
  if (!hydrated) return <main className="min-h-screen bg-canvas" />;

  if (!organization) return <main className="flex min-h-[calc(100vh-56px)] flex-col bg-canvas px-6 py-10"><section className="mx-auto flex w-full max-w-4xl flex-1 flex-col items-center justify-center text-center"><p className="eyebrow text-cyan">Security incident reasoning</p><h1 className="mt-4 text-4xl font-semibold tracking-tight">See the attack. Understand the story.</h1><p className="mt-4 max-w-xl text-slate-400">Create your first organization to map its architecture and begin an investigation.</p><Link href="/organizations/new" className="mt-8 rounded bg-primary px-4 py-2 text-sm font-medium text-white transition hover:bg-[#3d62ef]">Create Your First Organization</Link><section className="mt-14 w-full text-left"><p className="eyebrow text-cyan">How it works</p><div className="mt-3 grid gap-3 md:grid-cols-3">{howItWorks.map(([step, title, description]) => <article key={step} className="rounded-xl border border-border bg-panel p-4"><span className="font-mono text-[10px] text-cyan">STEP {step}</span><h2 className="mt-2 text-sm font-semibold text-slate-100">{title}</h2><p className="mt-2 text-xs leading-5 text-slate-400">{description}</p></article>)}</div></section></section><footer className="pt-8 text-center font-mono text-[10px] text-slate-600">Built with GPT-5.6 + Codex for OpenAI Build Week 2026</footer></main>;

  const totalHypotheses = investigations.reduce((total, item) => total + ((item.result as { hypotheses?: unknown[] }).hypotheses?.length ?? 0), 0);
  const totalGaps = investigations.reduce((total, item) => total + ((item.result as { evidenceGaps?: unknown[] }).evidenceGaps?.length ?? 0), 0);
  const stats = [["Total investigations", investigations.length, "text-cyan"], ["Total hypotheses generated", totalHypotheses, "text-primary"], ["Total evidence gaps identified", totalGaps, "text-medium"]];

  return <main className="min-h-[calc(100vh-56px)] bg-canvas px-5 py-7 sm:px-9"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow text-cyan">Organization dashboard</p><h1 className="mt-1 text-3xl font-semibold">{organization.name}</h1><p className="mt-2 text-sm text-slate-400">Monitor incident narratives and remaining evidence questions.</p></div><div className="flex gap-2"><Link href="/architecture" className="rounded border border-border bg-panel px-3 py-2 text-sm text-slate-300 hover:border-border-hover">Architecture</Link><Link href="/investigate" className="rounded bg-primary px-3 py-2 text-sm font-medium">+ New Investigation</Link></div></header><section className="mt-7 grid gap-3 sm:grid-cols-3">{stats.map(([label, value, color]) => <article key={String(label)} className="rounded-xl border border-border bg-panel p-4"><p className="font-mono text-[10px] uppercase tracking-wider text-slate-500">{label}</p><p className={`mt-2 text-3xl font-semibold ${color}`}>{value}</p></article>)}</section><section className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="text-sm font-semibold">Past investigations</h2><span className="font-mono text-[10px] text-slate-500">{investigations.length} TOTAL</span></div>{investigations.length === 0 ? <div className="rounded-xl border border-dashed border-border bg-panel p-8 text-center"><p className="text-sm text-slate-400">No investigations yet.</p><Link href="/investigate" className="mt-3 inline-block text-sm text-cyan">Run your first analysis →</Link></div> : <div className="grid gap-3 md:grid-cols-2">{investigations.map((investigation) => { const hypothesisCount = (investigation.result as { hypotheses?: unknown[] }).hypotheses?.length ?? 0; return <Link key={investigation.id} href={`/investigate/${investigation.id}`} className="rounded-xl border border-border bg-panel p-4 transition hover:border-border-hover hover:bg-panel-secondary"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] text-slate-500">{new Date(investigation.createdAt).toLocaleString()}</p><h3 className="mt-1 text-sm font-semibold">{investigation.title}</h3></div><span className={`rounded-full border px-2 py-1 font-mono text-[9px] uppercase ${severityStyles[investigation.severity]}`}>{investigation.severity}</span></div><p className="mt-3 font-mono text-[10px] text-slate-500">{hypothesisCount} HYPOTHESES · VIEW INVESTIGATION →</p></Link> })}</div>}</section></div></main>;
}
